//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "alert_rules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub brew_id: Option<Uuid>,
    pub hydrometer_id: Option<Uuid>,
    pub metric: String,
    pub operator: String,
    #[sea_orm(column_type = "Double")]
    pub threshold: f64,
    pub alert_target_id: Uuid,
    pub enabled: bool,
    pub cooldown_minutes: i32,
    pub last_triggered_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub window_hours: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::alert_targets::Entity",
        from = "Column::AlertTargetId",
        to = "super::alert_targets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AlertTargets,
    #[sea_orm(
        belongs_to = "super::brews::Entity",
        from = "Column::BrewId",
        to = "super::brews::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Brews,
    #[sea_orm(
        belongs_to = "super::hydrometers::Entity",
        from = "Column::HydrometerId",
        to = "super::hydrometers::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Hydrometers,
}

impl Related<super::alert_targets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertTargets.def()
    }
}

impl Related<super::brews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brews.def()
    }
}

impl Related<super::hydrometers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hydrometers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
