//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "brew_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub brew_id: Uuid,
    pub event_type: String,
    pub label: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub gravity_at_event: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub temp_at_event: Option<f64>,
    pub event_time: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::brews::Entity",
        from = "Column::BrewId",
        to = "super::brews::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Brews,
}

impl Related<super::brews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brews.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
