//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "nutrient_schedules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub brew_id: Uuid,
    #[sea_orm(column_type = "Double")]
    pub batch_size_gallons: f64,
    #[sea_orm(column_type = "Double")]
    pub og: f64,
    pub nitrogen_requirement: String,
    pub nutrient_protocol: String,
    #[sea_orm(column_type = "Double")]
    pub total_yan_ppm: f64,
    #[sea_orm(column_type = "Double")]
    pub go_ferm_yan_offset_ppm: f64,
    #[sea_orm(column_type = "Double")]
    pub fruit_yan_offset_ppm: f64,
    #[sea_orm(column_type = "Double")]
    pub effective_yan_ppm: f64,
    #[sea_orm(column_type = "Double")]
    pub go_ferm_grams: f64,
    #[sea_orm(column_type = "Double")]
    pub yeast_grams: f64,
    #[sea_orm(column_type = "Double")]
    pub rehydration_water_ml: f64,
    #[sea_orm(column_type = "Double")]
    pub one_third_break_sg: f64,
    pub alert_target_id: Option<Uuid>,
    pub max_dosage_capped: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::alert_targets::Entity",
        from = "Column::AlertTargetId",
        to = "super::alert_targets::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AlertTargets,
    #[sea_orm(
        belongs_to = "super::brews::Entity",
        from = "Column::BrewId",
        to = "super::brews::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Brews,
    #[sea_orm(has_many = "super::nutrient_additions::Entity")]
    NutrientAdditions,
}

impl Related<super::alert_targets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertTargets.def()
    }
}

impl Related<super::brews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brews.def()
    }
}

impl Related<super::nutrient_additions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NutrientAdditions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
