//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "nutrient_additions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub schedule_id: Uuid,
    pub addition_number: i32,
    #[sea_orm(column_type = "Double")]
    pub fermaid_o_grams: f64,
    #[sea_orm(column_type = "Double")]
    pub fermaid_k_grams: f64,
    #[sea_orm(column_type = "Double")]
    pub dap_grams: f64,
    pub trigger_type: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub target_hours: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub target_gravity: Option<f64>,
    pub notified_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::nutrient_schedules::Entity",
        from = "Column::ScheduleId",
        to = "super::nutrient_schedules::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    NutrientSchedules,
}

impl Related<super::nutrient_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NutrientSchedules.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
